apiVersion: apps/v1
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
kind:
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels: 
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers: 
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:  #port to be exposed
            - containerPort: 80    

# result app exposes port 80 because it's a web application
